CREATE TABLE IF NOT EXISTS events(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_name VARCHAR(100) NOT NULL,
  event_date DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS departments(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  department_name VARCHAR(100) NOT NULL,
);

CREATE TABLE IF NOT EXISTS aviaries(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  enclosure_number INTEGER,
  enclosure_area INTEGER NOT NULL,
);

CREATE TABLE IF NOT EXISTS visitors(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id INTEGER NOT NULL,
  visitor_name VARCHAR(100) NOT NULL,
  FOREIGN KEY (event_id) REFERENCES event(id)
  ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS employees(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  department_id INTEGER NOT NULL,
  position VARCHAR(100),
  employee_name VARCHAR(100),
  FOREIGN KEY (department_id) REFERENCES departments(id)
  ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS animals(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  enclosure_id INTEGER NOT NULL,
  animal_name VARCHAR(100) NOT NULL,
  FOREIGN KEY (enclosure_id) REFERENCES aviaries(id)
  ON DELETE CASCADE ON UPDATE NO ACTION
); 

CREATE TABLE IF NOT EXISTS rations(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  animal_id INTEGER NOT NULL,
  ration_date DATE,
  ration_contents VARCHAR(100),
  FOREIGN KEY (animal_id) REFERENCES animals(id)
  ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS nutrition(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ration_id INTEGER NOT NULL,
  food_name VARCHAR(100) NOT NULL,
  FOREIGN KEY (ration_id) REFERENCES rations(id)
  ON DELETE CASCADE ON UPDATE NO ACTION
); 

CREATE TABLE IF NOT EXISTS medical_card(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  animal_id INTEGER NOT NULL,
  examination_date DATE NOT NULL,
  diagnosis VARCHAR(100) NOT NULL,
  FOREIGN KEY (animal_id) REFERENCES animals(id)
  ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS types_of_animals(
  id INTEGER PRIMARY KEY AUTOINCREMENT, 
  animal_id INTEGER NOT NULL,
  special_name VARCHAR(100) NOT NULL,
  FOREIGN KEY (animal_id) REFERENCES animals(id)
  ON DELETE CASCADE ON UPDATE NO ACTION
);
